### ISSUE TITLE
请帮忙添加一下软件内购脚本

### ISSUE THREAD

**Issue by fangpidedongsun** [Alex0510/surge#10]
请求帮忙添加一下这几款软件的内购脚本，非常感谢。
Unread2
Enlight系列(photofox,videoleap)
Facetune2
Airmail
Timepage

**Comment by Alex0510** [comment]
不是所有的都可以破解内购的------------------ 原始邮件 ------------------
发件人: "fangpidedongsun"<notifications@github.com>
发送时间: 2020年3月24日(星期二) 上午9:18
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Alex0510/surge] 请帮忙添加一下软件内购脚本 (#10)




 
请求帮忙添加一下这几款软&#x4EF6;的内购脚本，非常感谢。
 Unread2
 Enlight系列(photofox,videoleap)
 Facetune2
 Airmail
 Timepage
 
&mdash;

**Comment by Alex0510** [comment]
自行测试airmail

发自我的iPhone

**Comment by fangpidedongsun** [comment]
airmail成功，感谢

**Comment by xjwhust** [comment]
> airmail成功，感谢
机器名在哪看呢 @fangpidedongsun

**Comment by Alex0510** [comment]
邮箱APP设置里面最下面------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月24日(星期二) 下午3:31
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] 请帮忙添加一下软件内购脚本 (#10)




  
airmail成功，感谢
 机器名在哪看呢 @fangpidedongsun
  
&mdash;

**Comment by xjwhust** [comment]
> 邮箱APP设置里面最下面------------------ 原始邮件 ------------------ 发件人: "xjwhust"<notifications@github.com> 发送时间: 2020年3月24日(星期二) 下午3:31 收件人: "Alex0510/surge"<surge@noreply.github.com>; 抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Alex0510/surge] 请帮忙添加一下软件内购脚本 (#10) airmail成功，感谢 机器名在哪看呢 @fangpidedongsun &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢~成功
