### ISSUE TITLE
speedtest好像恢复不了

### ISSUE THREAD

**Issue by shaGuar-svg** [Alex0510/surge#11]
测试过很多次、不知道哪里有问题？重写并没有命中。其他的测试都可以。就是用不上就删了

**Comment by xjwhust** [comment]
好的，明白，感谢~

**Comment by shaGuar-svg** [comment]
请问能修复吗？还是我操作的问题~

**Comment by Alex0510** [comment]
这个是国区的speedtest，不是美区的那个------------------ 原始邮件 ------------------
发件人: "shaGuar"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 凌晨0:55
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Alex0510/surge] speedtest好像恢复不了 (#11)




 
请问能修复吗？还是我操作的问题~
 
&mdash;
