### ISSUE TITLE
沙拉视频 恢复内购好像失效了

### ISSUE THREAD

**Issue by fangpidedongsun** [Alex0510/surge#15]
Mixyslvideo.js 脚本中沙拉视频恢复好像失效了

**Comment by Alex0510** [comment]
没有失效哦，测试正常------------------ 原始邮件 ------------------
发件人: "fangpidedongsun"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 下午3:20
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Alex0510/surge] 沙拉视频 恢复内购好像失效了 (#15)




 
Mixyslvideo.js 脚本中沙拉视频恢复好像失效了
 
&mdash;

**Comment by Alex0510** [comment]
![31923365-C9A3-49CF-889A-9807E9C06CC1](https://user-images.githubusercontent.com/22722447/77513215-8f41ae80-6eaf-11ea-81b9-885b3a3fe4b3.jpeg)
正常

**Comment by fangpidedongsun** [comment]
> ![31923365-C9A3-49CF-889A-9807E9C06CC1](https://user-images.githubusercontent.com/22722447/77513215-8f41ae80-6eaf-11ea-81b9-885b3a3fe4b3.jpeg)
> 正常

好奇怪哦，能看一下你的正则吗

**Comment by Alex0510** [comment]
http-response https:\/\/(viva|bmall)\.(v21xy|camera360)\.com\/api\/(rest/u/vip(VerifyReceipt|InfoNew)|iap/check-receipt|mix/getinfo) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Alex0510/surge/master/Script/Mixyslvideo.js,script-update-interval=0------------------ 原始邮件 ------------------
发件人: "fangpidedongsun"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 下午4:49
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] 沙拉视频 恢复内购好像失效了 (#15)




  

 正常
  
好奇怪哦，能看一下你的正则吗
 
&mdash;

**Comment by fangpidedongsun** [comment]
> http-response https:\/\/(viva|bmall)\.(v21xy|camera360)\.com\/api\/(rest/u/vip(VerifyReceipt|InfoNew)|iap/check-receipt|mix/getinfo) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Alex0510/surge/master/Script/Mixyslvideo.js,script-update-interval=0------------------ 原始邮件 ------------------ 发件人: "fangpidedongsun"<notifications@github.com> 发送时间: 2020年3月25日(星期三) 下午4:49 收件人: "Alex0510/surge"<surge@noreply.github.com>; 抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Alex0510/surge] 沙拉视频 恢复内购好像失效了 (#15) 正常 好奇怪哦，能看一下你的正则吗 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢。正则一样，后来发现是Reject.list 里面屏蔽了。谢谢
