### ISSUE TITLE
麻烦大神看看这两款软件能否破解，谢谢

### ISSUE THREAD

**Issue by fangpidedongsun** [Alex0510/surge#20]
https://apps.apple.com/cn/app/habitify-%E4%B9%A0%E6%83%AF%E8%B7%9F%E8%B8%AA%E5%99%A8/id1111447047

https://apps.apple.com/cn/app/lazy-bones-routine-planner/id1372737583

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Alex0510** [comment]
bones更新了自己测试一下，我没测试


发自我的iPhone

**Comment by fangpidedongsun** [comment]
测试成功，谢谢
