### ISSUE TITLE
可以帮忙试一下 [快知] APP吗

### ISSUE THREAD

**Issue by fangpidedongsun** [Alex0510/surge#27]

**Comment by Alex0510** [comment]
我想知道这个具体是干嘛的？看了一下不知道怎么玩------------------ 原始邮件 ------------------
发件人: "fangpidedongsun"<notifications@github.com>
发送时间: 2020年4月8日(星期三) 下午4:29
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Alex0510/surge] 可以帮忙试一下 [快知] APP吗 (#27)




 
&mdash;

**Comment by Alex0510** [comment]
看了半天没看明白干嘛用的

**Comment by fangpidedongsun** [comment]
哦哦 这个应用主要就是聚合信息用的 类似以前的即刻app 爬虫类app
他里面有很多机器人 你可以订阅机器人来关注你想关注的信息 比如XXX发微博了 这个应用就会给你发消息XXX发了什么什么微博
当然大神你可以在这个app里面创建自己的机器人 
但是你订阅几个热门的追踪机器人就需要会员了

**Comment by Alex0510** [comment]
订阅机器人破不了的，测试自慰的------------------ 原始邮件 ------------------
发件人: "fangpidedongsun"<notifications@github.com>
发送时间: 2020年4月8日(星期三) 晚上11:03
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] 可以帮忙试一下 [快知] APP吗 (#27)




 
哦哦 这个应用主要就是聚合信息用的 类似以前的即刻app 爬虫类app
 他里面有很多机器人 你可以订阅机器人来关注你想关注的信息 比如XXX发微博了 这个应用就会给你发消息XXX发了什么什么微博
 当然大神你可以在这个app里面创建自己的机器人
 但是你订阅几个热门的追踪机器人就需要会员了
 
&mdash;

**Comment by fangpidedongsun** [comment]
谢谢
