### ISSUE TITLE
不知能否添加一下Launch Center Pro的内购脚本

### ISSUE THREAD

**Issue by fangpidedongsun** [Alex0510/surge#8]
不知能否添加一下Launch Center Pro的内购脚本
谢谢

**Comment by Alex0510** [comment]
已增加

**Comment by Alex0510** [comment]
已增加内购恢复

发自我的iPhone

**Comment by fangpidedongsun** [comment]
> 已增加内购恢复
> 
> 发自我的iPhone
> 
> > 在 2020年3月23日，下午2:21，fangpidedongsun <notifications@github.com> 写道：
> > 
> > ﻿
> > 不知能否添加一下Launch Center Pro的内购脚本
> > 谢谢
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

非常感谢
